MNT Require queued job 4.7.x-dev and tweak travis
silverstripe/cwp-recipe-search pull request #17
Opened 2021-05-31 05:26 UTC by maxime-rainville

# Parent issue
https://github.com/silverstripe/recipe-blog/issues/24

2021-05-31 05:27 UTC, maxime-rainville commented on composer.json
> +        "symbiote/silverstripe-queuedjobs": "4.7.x-dev"
Confirm this get locksteped in the tag.

2021-05-31 22:02 UTC, emteknetnz commented on composer.json
> +        "symbiote/silverstripe-queuedjobs": "4.7.x-dev"
I'm not sure we should do this one.  Keeping recipes in step with each other makes sense because we'll only ever release a recipe minor during a quarterly release.  However queuedjobs could be incremented outside of this cycle.  I get that cow will sort this, though there's a decent chance we'll forget to increment queuedjobs

2021-05-31 22:02 UTC, emteknetnz requested changes
Not sure about this one.  Still makes sense to remove COMPOSER_ROOT_VERSION if nothing else

2021-06-03 03:39 UTC, maxime-rainville commented on composer.json
> +        "symbiote/silverstripe-queuedjobs": "4.7.x-dev"
When we ship a patch CWP/CMS release, we normally only ship patch releases of modules.

So if we did a 2.8.1 CWP patch release, we would ship another patch release of `queuedjobs` 4.7.* ... even if queued jobs 4.8.0 was available. That's why `cwp-recipe-search` 2.8.x should be testing `queuedjobs` 4.7.x.

2021-06-03 03:58 UTC, emteknetnz commented on composer.json
> +        "symbiote/silverstripe-queuedjobs": "4.7.x-dev"
Yeah I guess, it does match what we're doing here https://github.com/silverstripe/recipe-collaboration/blob/1.8/composer.json#L12

2021-06-03 03:58 UTC, emteknetnz approved these changes

2021-06-03 03:58 UTC, merged